/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/access': RouteRecordInfo<'/access', '/access', Record<never, never>, Record<never, never>>,
    '/direct-links': RouteRecordInfo<'/direct-links', '/direct-links', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logs': RouteRecordInfo<'/logs', '/logs', Record<never, never>, Record<never, never>>,
    '/rules': RouteRecordInfo<'/rules', '/rules', Record<never, never>, Record<never, never>>,
    '/s/[token]': RouteRecordInfo<'/s/[token]', '/s/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/shares': RouteRecordInfo<'/shares', '/shares', Record<never, never>, Record<never, never>>,
    '/uploads': RouteRecordInfo<'/uploads', '/uploads', Record<never, never>, Record<never, never>>,
    '/webdav': RouteRecordInfo<'/webdav', '/webdav', Record<never, never>, Record<never, never>>,
  }
}
