import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [
    ['btn', 'px-4 py-1 rounded inline-block bg-teal-700 text-white cursor-pointer !outline-none hover:bg-teal-800 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50'],
    ['icon-btn', 'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-teal-600'],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  safelist: [
    ...'prose prose-sm m-auto text-left'.split(' '),
    'i-fluent-add-24-regular',
    'i-fluent-arrow-move-24-regular',
    'i-fluent-arrow-up-24-regular',
    'i-fluent-chevron-down-24-regular',
    'i-fluent-chevron-right-24-regular',
    'i-fluent-clipboard-paste-24-regular',
    'i-fluent-cloud-24-regular',
    'i-fluent-copy-24-regular',
    'i-fluent-cut-24-regular',
    'i-fluent-database-24-regular',
    'i-fluent-delete-24-regular',
    'i-fluent-desktop-24-regular',
    'i-fluent-dismiss-24-regular',
    'i-fluent-folder-add-24-regular',
    'i-fluent-folder-arrow-right-24-regular',
    'i-fluent-hard-drive-24-regular',
    'i-fluent-home-24-regular',
    'i-fluent-more-horizontal-24-regular',
    'i-fluent-open-24-regular',
    'i-fluent-people-team-24-regular',
    'i-fluent-rename-24-regular',
    'i-vscode-icons-default-file',
    'i-vscode-icons-default-folder',
    'i-vscode-icons-file-type-excel',
    'i-vscode-icons-file-type-image',
    'i-vscode-icons-file-type-json',
    'i-vscode-icons-file-type-markdown',
    'i-vscode-icons-file-type-pdf2',
    'i-vscode-icons-file-type-photoshop',
    'i-vscode-icons-file-type-powerpoint',
    'i-vscode-icons-file-type-text',
    'i-vscode-icons-file-type-video',
    'i-vscode-icons-file-type-word',
    'i-vscode-icons-file-type-zip',
  ],
})
